site:
  title: Red Hat Satellite Break-fix Practice 4 (FIXME)
  start_page: satellite-bfx-004::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
