= Guided solution (page 1 of 1)
:experimental:

== Objectives

* Investigate what is the issue tftp in satellite.
* Solve the directory issue of tftp and allowing satellite-installer to complete successfully in the hands-on lab environment.

== Instructions

Run following instructions on `satellite` system with `root` as user.

.Sample output:
----
[ec2-user@satellite ~]$ sudo su -
[root@satellite ~]#
----

* ISSUE: `/var/log/foreman-installer/satellite.log` shows:
+
.Sample output:
----
[ ERROR ] [configure] Cannot create /var/lib/tftpboot/pxelinux.cfg,/var/lib/tftpboot/grub,/var/lib/tftpboot/grub2,/var/lib/tftpboot/boot,/var/lib/tftpboot/ztp.cfg,/var/lib/tftpboot/poap.cfg; parent directory /var/lib/tftpboot/pxelinux.cfg,/var/lib/tftpboot/grub,/var/lib/tftpboot/grub2,/var/lib/tftpboot/boot,/var/lib/tftpboot/ztp.cfg,/var/lib/tftpboot does not exist
----


The error indicates some issue with the tftp directories. If we inspect the `/etc/foreman-installer/scenarios.d/satellite-answers.yaml` file we can see that the tftp_dirs paramerter is defined in an incorrect way. +
The correct way to define an array in yaml would be: +
----
tftp_dirs: 
- "/var/lib/tftpboot/pxelinux.cfg" 
- "/var/lib/tftpboot/grub" 
- "/var/lib/tftpboot/grub2" 
- "/var/lib/tftpboot/boot" 
- "/var/lib/tftpboot/ztp.cfg" 
- "/var/lib/tftpboot/poap.cfg"
----
As an alternative, this can also be defined via satellite-installer as:
[source,bash,role=execute]
----
satellite-installer \ 
--foreman-proxy-tftp-dirs  /var/lib/tftpboot/pxelinux.cfg \ 
--foreman-proxy-tftp-dirs /var/lib/tftpboot/grub \ 
--foreman-proxy-tftp-dirs /var/lib/tftpboot/grub2 \ 
--foreman-proxy-tftp-dirs /var/lib/tftpboot/boot \ 
--foreman-proxy-tftp-dirs /var/lib/tftpboot/ztp.cfg \ 
--foreman-proxy-tftp-dirs /var/lib/tftpboot/poap.cfg
----

The command should complete successfully:

.Sample output:
----
2025-02-11 07:59:28 [NOTICE] [configure] System configuration has finished.
  Success!
  * Satellite is running at https://satellite.xxx.yyy
----